### ISSUE TITLE
Feature Suggestion: Specify Run Ids

### ISSUE THREAD

**Issue by Macavity** [ArchitectNow/cypress-testrail-reporter#79]
It seems the reporter finds all run ids which match for the given project and plan id and include the matching test cases, and after the tests are run reports to all of those runs that the test cases have passed/failed.

Our setup uses different devices/browsers as part of one test plan.
For example: Test Plan 1, has 2 Test Runs C for Chrome and F for Firefox. We now have tests which check if everything works for Chrome and Firefox in separated Test Runs.

What do you think about allowing to configure a Run ID alternatively to the Plan ID in the reporterOptions. 
If the planId is provided the behaviour stays as it is currently.
If the runId is provided, it will only update the test cases of this runId.

**Comment by nartc** [comment]
I see. I’ll take a look to evaluate a couple of solutions for this feature. Thanks!

**Comment by Macavity** [comment]
Actually I already have a branch which implements this, I just wanted to check if you want a PR for this ;-)

**Comment by nartc** [comment]
> Actually I already have a branch which implements this, I just wanted to check if you want a PR for this ;-)

Go for it. I will review
